name: arcxp-test
services:
  localstack:
    container_name: arcxp-localstack-test
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4576:4566"            # LocalStack Gateway (shifted from 4566)
      - "127.0.0.1:4520-4569:4510-4559"  # external services port range (shifted)
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./scripts/localstack:/etc/localstack/init/ready.d"
