name: Deploy to Lambda

on:
  push:
    branches:
      - main
  # Optional: for PR merges
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ACCOUNT_ID: 846447858735
      PROFILE: personal

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-lambda
        run: |
          curl -s https://raw.githubusercontent.com/cargo-lambda/cargo-lambda/main/tools/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Make + dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y make unzip

      - name: Deploy Lambda
        run: make lambda
